version: '3.9'
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: 'mnpl'
      POSTGRES_USER: 'mnpl'
      POSTGRES_PASSWORD: 'mnpl'
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
